ejemplo_django/blog/urls.py
from django.conf.urls import url,include
from . import views
from .datatables_views import *

urlpatterns = [

    
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_page, name='login_page'),
    url(r'^login/auth$', views.login_user, name='login_user'),
    url(r'^logout/$', views.logout_user, name='logout'),


    #main
    url(r'^main/$', views.main, name='main'),


    #gets
    url(r'^getNewCiudades/$', views.getNewCiudades, name='getNewCiudades'),

    #usuarios
    url(r'^usuarios/$', views.usuarios, name='usuarios'),
    url(r'^usuarios/agregar/$', views.usuarios_agregar, name='usuarios_agregar'),
    url(r'^usuarios/guardar$', views.usuarios_guardar, name='usuarios_guardar'),
    url(r'^usuarios/serverside$', DTUsuarios.as_view(), name='DTUsuarios'),
    url(r'^usuarios/editar/(?P<id_tipo>[-\w]+)$', views.usuarios_editar, name='usuarios_editar'),
    url(r'^usuarios/editar_usuario/guardar$', views.usuarios_editar_guardar, name='usuarios_editar_guardar'),
    url(r'^usuarios/eliminar/(?P<id_tipo>[-\w]+)$', views.usuarios_eliminar, name='usuarios_eliminar'),
    url(r'^usuarios/eliminar/ok$', views.usuarios_eliminar_ok, name='usuarios_eliminar_ok'),

    #clientes
    url(r'^clientes/$', views.clientes, name='usuarios'),
    url(r'^clientes/agregar/$', views.clientes_agregar, name='clientes_agregar'),
    url(r'^clientes/guardar$', views.clientes_guardar, name='clientes_guardar'),
    url(r'^clientes/serverside$', DTClientes.as_view(), name='DTClientes'),
    url(r'^clientes/editar/(?P<id_tipo>[-\w]+)$', views.clientes_editar, name='clientes_editar'),
    url(r'^clientes/editar_cliente/guardar$', views.clientes_editar_guardar, name='clientes_editar_guardar'),
    url(r'^clientes/eliminar/(?P<id_tipo>[-\w]+)$', views.clientes_eliminar, name='usuarios_eliminar'),
    url(r'^clientes/eliminar/ok$', views.clientes_eliminar_ok, name='clientes_eliminar_ok'),
    

    #sucursales
    url(r'^sucursales/$', views.sucursales, name='sucursales'),
    url(r'^sucursales/serverside$', DTSucursales.as_view(), name='DTSucursales'),
    url(r'^sucursales/agregar/$', views.sucursales_agregar, name='sucursales_agregar'),
    url(r'^sucursales/guardar$', views.sucursales_guardar, name='sucursales_guardar'),
    url(r'^sucursales/editar/(?P<id_tipo>[-\w]+)$', views.sucursales_editar, name='sucursales_editar'),
    url(r'^sucursales/editar_sucursal/guardar$', views.sucursales_editar_guardar, name='sucursales_editar_guardar'),
    url(r'^sucursales/eliminar/(?P<id_tipo>[-\w]+)$', views.sucursales_eliminar, name='sucursales_eliminar'),
    url(r'^sucursales/eliminar/ok$', views.sucursales_eliminar_ok, name='sucursales_eliminar_ok'),

    #ordenes
    url(r'^ordenes/$', views.ordenes, name='ordenes'),
    url(r'^ordenes/agregar/$', views.ordenes_agregar, name='ordenes_agregar'),
    url(r'^ordenes/guardar$', views.ordenes_guardar, name='ordenes_guardar'),
    url(r'^ordenes/serverside$', DTOrden.as_view(), name='DTOrden'),
    url(r'^ordenes/editar/(?P<id_tipo>[-\w]+)$', views.ordenes_editar, name='ordenes_editar'),
    url(r'^ordenes/editar_orden/guardar$', views.ordenes_editar_guardar, name='ordenes_editar_guardar'),
    url(r'^ordenes/eliminar/(?P<id_tipo>[-\w]+)$', views.ordenes_eliminar, name='ordenes_eliminar'),
    url(r'^ordenes/eliminar/ok$', views.ordenes_eliminar_ok, name='ordenes_eliminar_ok'),

    #tecnicos
    url(r'^tecnicos/$', views.tecnicos, name='tecnicos'),
    url(r'^tecnicos/agregar/$', views.tecnicos_agregar, name='tecnicos_agregar'),
    url(r'^tecnicos/guardar$', views.tecnicos_guardar, name='tecnicos_guardar'),
    url(r'^tecnicos/serverside$', DTTecnico.as_view(), name='DTTecnico'),
    url(r'^tecnicos/editar/(?P<id_tipo>[-\w]+)$', views.tecnicos_editar, name='ordenes_editar'),
    url(r'^tecnicos/editar_tecnico/guardar$', views.tecnicos_editar_guardar, name='tecnicos_editar_guardar'),
    url(r'^tecnicos/eliminar/(?P<id_tipo>[-\w]+)$', views.tecnicos_eliminar, name='tecnicos_eliminar'),
    url(r'^tecnicos/eliminar/ok$', views.tecnicos_eliminar_ok, name='tecnicos_eliminar_ok'),

    #TAREAS
    url(r'^pendientes/$', views.pendientes, name='pendientes'),
    url(r'^tareas/serverside$', DTTareas.as_view(), name='DTTareas'),
    url(r'^crearTarea$', views.crearTarea, name='crearTarea'),
    url(r'^terminarTarea$', views.terminarTarea, name='terminarTarea'),
    url(r'^cancelarTarea$', views.cancelarTarea, name='cancelarTarea'),

    #contactos
    url(r'^contactos/$', views.contactos, name='contactos'),
    url(r'^contactos/serverside$', DTContacto.as_view(), name='DTContacto'),
    url(r'^contactos/agregar/$', views.contactos_agregar, name='contactos_agregar'),
    url(r'^contactos/guardar$', views.contactos_guardar, name='contactos_guardar'),
    url(r'^contactos/editar/(?P<id_tipo>[-\w]+)$', views.contactos_editar, name='contactos_editar'),
    url(r'^contactos/editar_contacto/guardar$', views.contactos_editar_guardar, name='contactos_editar_guardar'),
    url(r'^contactos/eliminar/(?P<id_tipo>[-\w]+)$', views.contactos_eliminar, name='contactos_eliminar'),
    url(r'^contactos/eliminar/ok$', views.contactos_eliminar_ok, name='contactos_eliminar_ok'),


    #TAREAS
    url(r'^estadisticas/$', views.estadisticas, name='estadisticas'),
    url(r'^getOrdenes/$', views.getOrdenes, name='getOrdenes'),

]

ejemplo_django/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^$', views.mainaux, name='mainaux'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
]

ejemplo_django/blog/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from datetime import datetime,timedelta,date
from django.db.models.deletion import Collector
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from .models import *

# Create your views here.


def index(request):
    return redirect('/blog/login/')


def login_aux(request):
    print(settings.STATIC_ROOT)
    return redirect('/blog/login/')


def login_page(request):
    return render(request,
                  'login/login.html', {'error': ''})

def login_user(request):
    if request.method == 'POST':
        username = request.POST['user']
        password = request.POST['password']

        print(username)
        print(password)
        user = authenticate(username=username, password=password)
        print(user)
        if user is not None and user.is_active:
            print("si")
            if Usuario.objects.filter(user=user.id).exists():
                rol = Usuario.objects.get(user=user.id)
                request.session['userrol'] = rol.rol.nombre
                print("asldkjasldkjasldjk")
                return redirect('/blog/main/')
            else:
                return render(request,'login/login.html',{'error':'Error de inicio de sesión de usuario, el usuario no existe o las credenciales son incorrectas'})
        else:
            return render(request,'login/login.html', {'error': 'Error de inicio de sesión de usuario, el usuario no existe o las credenciales son incorrectas'})
        
    else:
        return render(request,'login/login.html', {'error': 'You must use POST to login'})
        

def logout_user(request):
    if request.user.is_authenticated():
        return redirect('/blog/login')
    else:
        return redirect('/blog/main')

def main(request):
    return render(request,
                  'main/main.html', {'error': ''})

def usuarios(request):
    return render(request,'usuarios/main.html',{'error':''})

def usuarios_agregar(request):
    return render(request,
                  'usuarios/agregar.html', {'error': ''})

def usuarios_guardar(request):
    if request.method == "POST":

        nombre = request.POST['nombre']
        apellido = request.POST['apellido']
        telefono = request.POST['telefono']
        username = request.POST['username']
        password = request.POST['password']

        objUsuario = Usuario.objects.create()

        nuser = User.objects.create_user(username, '', password)
        nuser.last_name = apellido
        nuser.is_active = True
        objUsuario.nombre = nombre
        objUsuario.user= nuser
        objUsuario.apellido = apellido
        objUsuario.telefono = telefono

        objUsuario.save()
        return render(request,'usuarios/main.html',{'error':'','hecho':True})
    else:
        return render(request,'usuarios/main.html',{'error':True})

def usuarios_editar(request,id_tipo):
    if Usuario.objects.filter(id=id_tipo).exists():
        objUsuario = Usuario.objects.get(id=id_tipo)
        print(objUsuario)
        return render(request,'usuarios/editar.html',{'error':'','obj':objUsuario})
    else:
        return render(request,'usuarios/main.html',{'error':True})

def usuarios_editar_guardar(request):
    if request.method == "POST":
        print(request.POST)
        idUsuario = request.POST['idUsuario']
        nombre = request.POST['nombre']
        apellido = request.POST['apellido']
        telefono = request.POST['telefono']

        objUsuario = Usuario.objects.get(id=idUsuario)

        objUsuario.nombre = nombre
        objUsuario.apellido = apellido
        objUsuario.telefono = telefono

        objUsuario.save()
        return render(request,'usuarios/main.html',{'error':'','hecho':True})
    else:
        return render(request,'usuarios/main.html',{'error':True})

def usuarios_eliminar(request,id_tipo):
    if Usuario.objects.filter(id=id_tipo).exists():
        error = False
        objUsuario = Usuario.objects.get(id=id_tipo)
        print(objUsuario)

        collector = Collector(using='default')
        try:
            collector.collect([Usuario])
        except Exception as e:
            error = True
            print(e)
        return render(request,'usuarios/eliminar.html',{'error':error,'obj':objUsuario})
    else:
        return render(request,'usuarios/main.html',{'error':True})

def usuarios_eliminar_ok(request):
    if request.method == "POST":
        idUsuario = request.POST['idUsuario']

        objUsuario = Usuario.objects.get(id=idUsuario)
        objUsuario.delete()
        return render(request,'usuarios/main.html',{'error':'','hecho':True})

def clientes(request):
    return render(request,'clientes/main.html',{'error':''})

def clientes_agregar(request):
    estados = Estado.objects.all()
    ciudades = Ciudad.objects.all()
    return render(request,
                  'clientes/agregar.html', {'error': '','estados':estados,'ciudades':ciudades})

def clientes_guardar(request):
    if request.method == "POST":

        codigo = request.POST['codigo']
        razonsocial = request.POST['razonsocial']
        rfc = request.POST['rfc']
        estado = request.POST['estado']
        ciudad = request.POST['ciudad']
        calle = request.POST['calle']
        numeroexterior = request.POST['nexterior']
        numerointerior = request.POST['ninterior']
        cp = request.POST['cp']
        direccioncompleta = request.POST['direccion']

        objCliente = Cliente.objects.create()

        objCliente.codigo = codigo
        objCliente.razonsocial = razonsocial
        objCliente.rfc = rfc
        #objCliente.estado = Estado.objects.get(id=estado)
        #objCliente.ciudad = Ciudad.objects.get(id=ciudad)
        objCliente.calle = calle
        objCliente.numeroexterior = numeroexterior
        objCliente.numerointerior = numerointerior
        objCliente.cp = cp
        objCliente.direccioncompleta = direccioncompleta
        
        objCliente.save()
        return render(request,'clientes/main.html',{'error':'','hecho':True})
    else:
        return render(request,'clientes/main.html',{'error':True})

def clientes_editar(request,id_tipo):
    if Cliente.objects.filter(id=id_tipo).exists():
        objCliente = Cliente.objects.get(id=id_tipo)
        print(objCliente)
        return render(request,'clientes/editar.html',{'error':'','obj':objCliente})
    else:
        return render(request,'clientes/main.html',{'error':True})

def clientes_editar_guardar(request):
    if request.method == "POST":
        print(request.POST)
        idCliente = request.POST['idCliente']
        codigo = request.POST['codigo']
        razonsocial = request.POST['razonsocial']
        rfc = request.POST['rfc']
        estado = request.POST['estado']
        ciudad = request.POST['ciudad']
        calle = request.POST['calle']
        numeroexterior = request.POST['nexterior']
        numerointerior = request.POST['ninterior']
        cp = request.POST['cp']
        direccioncompleta = request.POST['direccion']

        objCliente = Cliente.objects.get(id=idCliente)

        objCliente.codigo = codigo
        objCliente.razonsocial = razonsocial
        objCliente.rfc = rfc
        #objCliente.estado = Estado.objects.get(id=estado)
        #objCliente.ciudad = Ciudad.objects.get(id=ciudad)
        objCliente.calle = calle
        objCliente.numeroexterior = numeroexterior
        objCliente.numerointerior = numerointerior
        objCliente.cp = cp
        objCliente.direccioncompleta = direccioncompleta

        objCliente.save()
        return render(request,'clientes/main.html',{'error':'','hecho':True})
    else:
        return render(request,'clientes/main.html',{'error':True})

def clientes_eliminar(request,id_tipo):
    if Cliente.objects.filter(id=id_tipo).exists():
        error = False
        objCliente = Cliente.objects.get(id=id_tipo)
        print(objCliente)

        collector = Collector(using='default')
        try:
            collector.collect([Usuario])
        except Exception as e:
            error = True
            print(e)
        return render(request,'clientes/eliminar.html',{'error':error,'obj':objCliente})
    else:
        return render(request,'clientes/main.html',{'error':True})

def clientes_eliminar_ok(request):
    if request.method == "POST":
        idCliente = request.POST['idCliente']

        objCliente = Usuario.objects.get(id=idCliente)
        objCliente.delete()
        return render(request,'clientes/main.html',{'error':'','hecho':True})


def sucursales(request):
    return render(request,'sucursales/main.html',{'error':''})

def sucursales_agregar(request):
    clientes = Cliente.objects.all()
    estados = Estado.objects.all()
    ciudades = Ciudad.objects.all()
    return render(request,
                  'sucursales/agregar.html', {'error': '','clientes':clientes,'estados':estados,'ciudades':ciudades})

def sucursales_guardar(request):
    if request.method == "POST":

        codigo = request.POST['codigo']
        cliente = request.POST['cliente']
        representante = request.POST['representante']
        estado = request.POST['estado']
        ciudad = request.POST['ciudad']

        calle = request.POST['calle']
        numeroexterior = request.POST['nexterior']
        numerointerior = request.POST['ninterior']
        cp = request.POST['cp']

        objSucursal = Sucursal.objects.create()

        objSucursal.codigo = codigo
        objSucursal.cliente = Cliente.objects.get(id=cliente)
        objSucursal.representante = representante
        objSucursal.estado = Estado.objects.get(id=estado)
        objSucursal.ciudad = Ciudad.objects.get(id=ciudad)
        objSucursal.calle = calle
        objSucursal.numeroexterior = numeroexterior
        objSucursal.numerointerior = numerointerior
        objSucursal.cp = cp
        
        objSucursal.save()

ejemplo_django/blog/templates/usuarios/main.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>SGOS</title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="/blog/main" class="site_title"><i class="fa fa-paw"></i> <span>SGOS</span></a>
            </div>

            <div class="clearfix"></div>

          

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-home"></i> Home</a></li>
                  <li><a  href="/blog/usuarios/"><i class="fa fa-user"></i> Usuarios</a></li> 
                  <li><a  href="/blog/clientes/"><i class="fa fa-user"></i> Clientes</a></li>   
                  <li><a  href="/blog/sucursales/"><i class="fa fa-user"></i> Sucursales</a></li>      
                  <li><a  href="/blog/ordenes/"><i class="fa fa-user"></i> Orden de Servicio</a></li>   
                  <li><a  href="/blog/tecnicos/"><i class="fa fa-user"></i> Técnicos </a></li> 
                  <li><a  href="/blog/pendientes/"><i class="fa fa-user"></i> Tareas </a></li>        
                  <li><a  href="/blog/contactos/"><i class="fa fa-user"></i> Contactos </a></li>     
                  <li><a  href="/blog/estadisticas/"><i class="fa fa-user"></i> Estadísticas </a></li>                     
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <div class="nav toggle">
                  <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                </div>
                <nav class="nav navbar-nav">
                <ul class=" navbar-right">
                  <li role="presentation" class="nav-item dropdown open">
                    
                </ul>
              </nav>
            </div>
          </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Usuarios</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5   form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Buscar</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

                <div class="row">
                    <div class="col-md-12 col-sm-12  ">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Administrador de Clientes</h2>
                        
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            {% if hecho %}
                                <div class="alert alert-success" role="alert">
                                    <a class="alert-link">Cambios hechos</a>.
                                </div>
                            {% endif %}
                            {% if error %}
                                <div class="alert alert-danger" role="alert">
                                    <a class="alert-link">Ha habido un error con la petición</a>.
                                </div>
                            {% endif %}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="panel">
                                        <div class="table-responsive">
                                           
                                            <table id="tabla_usuarios" class="table color-table color-bordered-table inverse-bordered-table table-hover table-striped manage-u-table" style="font-size: 1.0em;">
                                                <thead>
                                                    <tr>
                                                        <th>Usuario</th>
                                                        <th>Nombre</th>
                                                        <th>Apellido</th>   
                                                        <th>Opciones</th>                                            
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button id="cmdInsert" type="button" class="btn btn-primary btn-blue   pull-right" style="background-color: #1CA261 !important; border-color: #1CA261 !important">Agregar</button>
                    <br><br>
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
    <script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
    <script src="{% static 'build/js/custom.min.js' %}"></script>
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'js/axios.min.js' %}"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script> 
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.html5.min.js"></script>   
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>   
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>  


    <script type="text/javascript">
        $("#cmdInsert").click(function(){
            document.location = "/blog/usuarios/agregar/";
        });

        
        $(document).ready(function(){ 
            var TCS = $('#tabla_usuarios').DataTable({
                serverSide: true,
                "searching": false,
                oLanguage: {
                    sProcessing: '<img src="{% static "images/Preloader.gif" %}" alt="">'
                },
                processing : true,
                dom: 'lfrtipB',
                buttons: [
                    {
                        extend : 'pdf',
                        "text": '<button type="button" class="btn btn-primary btn-blue">Exportar PDF</button>',
                        title: "Ordenes",
                        exportOptions : {
                            modifier : {
                                // DataTables core
                                order : 'index',  // 'current', 'applied', 'index',  'original'
                                page : 'all'      // 'all',     'current'
                                
                                //search : 'none'     // 'none',    'applied', 'removed'
                            }
                        }
                    },
                    {
                        extend : 'excel',
                        "text": '<button type="button" class="btn btn-primary btn-blue">Exportar Excel</button>',
                        title: "Sucursales",
                        exportOptions : {
                            modifier : {
                                // DataTables core
                                order : 'index',  // 'current', 'applied', 'index',  'original'
                                page : 'all'      // 'all',     'current'
                                
                                //search : 'none'     // 'none',    'applied', 'removed'
                            }
                        }
                    }
                ],
                retrieve: true,
                "ajax": {
                    "url": "{% url 'blog:DTUsuarios' %}",
                    "type": "POST",
                    "data": {
                        'csrfmiddlewaretoken':"{{ csrf_token }}",
                    },                                
                },
                "columns":[
                    { "data" : "usuario"},
                    { "data" : "nombre"},
                    { "data" : "apellido"}, 
                    { "data" : "opciones"},        
                    
                ],
                "columnDefs": [ ],
                "order": []
            });

            /*$(document).on('change','#fechaInicio',function(){
                var list_inputs = [];   
                list_inputs.push($("#fechaInicio").val());
                list_inputs.push($("#fechaFin").val());


                TCS.search(list_inputs.join('|'), true, false, true).draw();
            });
            $(document).on('change','#fechaFin',function(){
                var list_inputs = [];   
                list_inputs.push($("#fechaInicio").val());
                list_inputs.push($("#fechaFin").val());

                TCS.search(list_inputs.join('|'), true, false, true).draw();
            });*/
        });

    </script>
  </body>
</html>